### ISSUE TITLE
[EPIC] 도메인 구성한다.

### ISSUE THREAD

**Issue by KimGyeong** [Double-Slash/5th-mini-team4-server#6]
## 제목
도메인 구성한다.
## 작업 내용
- [x] 질문 도메인을 구현한다. #1 
- [x] 응답 도메인을 구현한다. #2 
- [x] 카테고리 도메인을 구현한다. #3 
- [x] 평가 도메인을 구현한다. #4 
- [ ] 사용자 도메인을 구현한다. #5
